Set up CI with Azure Pipelines
[skip ci]

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -25,4 +25,22 @@ steps:
     script: 'sudo apt-get install azure-functions-core-tools-3'
 - task: CmdLine@2
   inputs:
-    script: 'func azure functionapp publish tonypythonfunc'
+    script: 'func azure functionapp publish tonypythonfunc --python'
+  
+- task: Bash@3
+  inputs:
+    targetType: 'inline'
+    script: |
+      for (( i = 0; [$? != 0] && [$i < 10]; i++ ))
+      do
+        # Echoes in Red
+        echo -e "\e[31mFailed. Waiting 1 minute and trying again...\e[0m"
+        sleep 1m
+        func azure functionapp publish tonypythonfunc --python
+      done
+      
+      if [[ $? != 0 ]]
+      then
+        echo "Too many failures while trying to deploy $app"
+        exit 1
+      fi
