Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -17,12 +17,19 @@ steps:
   inputs:
     targetType: 'inline'
     script: |
-      for (( i=0; i<10; ++i));
+      for (( i = 0; [$? != 0] && [$i < 10]; i++ ));
       do
         # Echoes in Red
         echo "Waiting 1 minute and trying again..."
         sleep 1m
+        func azure functionapp publish tonypythonfunc --python
       done
+
+      if [[ $? != 0 ]]
+      then
+        echo "Too many failures while trying to deploy $app"
+        exit 1
+      fi
 - script: |
     echo Add other tasks to build, test, and deploy your project.
     echo See https://aka.ms/yaml
